import "./globals.css";

export const metadata = {
  title: "r/cscareerquestions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="md:w-3/4 md:mx-auto xl:w-1/2">{children}</body>
    </html>
  );
}
